### PR TITLE
Symfony2.2 Documentation!

### PR DESCRIPTION
**Pull request by maddo**

### CODE REVIEW

**Comment by cordoval** [comment]
:baby:

approved :+1:

**Comment by maddo** [comment]
http://cl.ly/image/281a361E3o0y

Oops, I put some ugly <br> in the output. Fix coming!

**Comment by maddo** [comment]
Screenshot

**Comment by cordoval** [comment]
:+1:  what are we waiting guys? merge please and release

oh wait i will add packagist and knpbundles

**Comment by cordoval** [comment]
@maddo  i think at this point we have departed completely and it is no longer a PR but a personal workflow maybe?
If we add our own personal workflow stuff for our own documentation then we should fork it and make it private.

**Comment by cfeduke** [comment]
Syd any particular reason why this hasn't been merged yet? I don't know enough about Symfony2 to make a decision but things here look legit. The only bear is of course the Alfred plist file since Alfred likes to arbitrarily re-arrange the contents of that file.

**Comment by maddo** [comment]
@cfeduke yea, that gave me a bit of a scare the first time I saw the diff. A bit nasty looking, but should work fine :)

**Pull request merged**
